project/config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('libreria.urls'))
]

project/libreria/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
from django.conf import settings

app_name = "libreria"

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('nosotros', views.nosotros, name='nosotros'),
    path('libros', views.libros, name='libros'),
    path('libros/crear', views.crear, name='crear'),
    path('libros/editar', views.editar, name='editar'),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("register/", views.register, name="register"),
    path("logout/", LogoutView.as_view(template_name="libros/logout.html"), name="logout"),


]

project/libreria/models.py
from typing import Any
from django.db import models

# Create your models here.
class Libro(models.Model):
    id = models.AutoField(primary_key=True)
    titulo = models.CharField (max_length=100, verbose_name='Título')
    imagen = models.ImageField(upload_to='imagenes/',verbose_name="imagen", null=True,blank=True)
    descripcion = models.TextField(verbose_name="Descipción",null=True)
    
    def __str__(self):
        fila = "Título: " + self.titulo
        return fila
    
    def delete(self, using=None, keep_parents=False):
        self.imagen.storage.delete(self.imagen.name)
        super().delete()

project/libreria/forms.py
from django import forms
from .models import Libro
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User



class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username","password"]

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username","password1", "password2"]

project/libreria/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpRequest
from .models import Libro
from django.contrib.auth.views import LoginView
from .forms import CustomAuthenticationForm, CustomUserCreationForm
from django.contrib.auth.decorators import login_required

# Create your views here.

def inicio(request):
    return render(request, 'paginas/inicio.html')

def nosotros(request):
    return render(request, 'paginas/nosotros.html')

@login_required
def libros(request):
    libros = Libro.objects.all()
    return render(request, 'libros/index.html', {'libros': libros})

@login_required
def crear(request):
    return render(request, 'libros/crear.html')

@login_required
def editar(request):
    return render(request, 'libros/editar.html')

class CustomLoginView(LoginView):
    authentication_form = CustomAuthenticationForm
    template_name = "libros/login.html"
    next_page = "template/base.html"

def register(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('libreria:inicio') 
    else:
        form = CustomUserCreationForm()
    return render(request, "libros/register.html", {"form": form})

project/libreria/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <title> 
            {% block titulo %}  
            {% endblock %} 
        </title>
        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <!-- Bootstrap CSS v5.2.1 -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous"
        />
    </head>

    
    {% block content %}
    <body>
        <nav class="navbar navbar-expand navbar-light bg-light">
            <div class="nav navbar-nav">
                <a class="nav-item nav-link active" href="{% url 'libreria:inicio' %}">Inicio </a>
                <a class="nav-item nav-link active" href="{% url 'libreria:libros' %}">Libros </a>
                <a class="nav-item nav-link active" href="{% url 'libreria:nosotros' %}">Nosotros </a>
            </div>
            <div class="nav navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <form action="{% url 'libreria:logout' %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="nav-link nav-item">Cerrar Sesion</button>
                    </form>
                {% else %}
                    <a class="nav-item nav-link" href="{% url 'libreria:login' %}">Iniciar Sesión</a>
                    <a class="nav-item nav-link" href="{% url 'libreria:register' %}">Registrarse</a>
                {% endif %}
            </div>
        </nav>
        
        
        
        <div class="container">
            <div class="row">
                <div class="col-12">
                    {% block contenido %}  {% endblock %}
                </div>
            </div>
        </div>
        
        
        
        
        
        <header>
            <!-- place navbar here -->
        </header>
        <main></main>
        <footer>
            <!-- place footer here -->
        </footer>
        <!-- Bootstrap JavaScript Libraries -->
        <script
        src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"
        ></script>
        
        <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"
        ></script>
        {% endblock content %}
    </body>
    </html>
    

project/libreria/templates/libros/crear.html
{% extends "base.html" %}

{% block titulo %}  Agregar nuevo libro  {% endblock %}

{% block contenido %}

<div class="card">
    <div class="card-header">Crear un libro</div>
    <div class="card-body">
        <h4 class="card-title">Datos del libro</h4>
        {% include 'libros/form.html' %}


    </div>
    <div class="card-footer text-muted"></div>
</div>


{% endblock %}

project/libreria/templates/libros/editar.html
{% extends "base.html" %}

{% block titulo %}  Editar libro  {% endblock %}

{% block contenido %}

<div class="card">
    <div class="card-header">Editar información del libro</div>
    <div class="card-body">
        <h4 class="card-title">Datos del libro</h4>
        {% include 'libros/form.html' %}


    </div>
    <div class="card-footer text-muted"></div>
</div>

{% endblock %}

project/libreria/templates/libros/form.html
<form enctype="multipart/form-data" method="post">

{% csrf_token %}
{% for campo in formulario %}

<div class="mb-3">
    <label for="" class="form-label">Nombre:</label>
    <input
        type=" {{ campo.field.widget.input_type }}"
        class="form-control"
        name=""
        id=""
        aria-describedby="helpId"
        placeholder="Nombre"
    />
    
</div>
{% endfor %}

</form>

project/libreria/templates/libros/index.html
{% extends "base.html" %}

{% block titulo %} Lista de libros {% endblock %}

{% block contenido %}

<div class="card">
    <div class="card-header">

        <a name="" id="" class="btn btn-success" href="{% url 'libreria:crear' %}" role="button">Agregar nuevo libro</a>


    </div>
    <div class="card-body">
        <h4 class="card-title">Libros</h4>

        <div class="table-responsive">
            <table class="table table-primary">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Título</th>
                        <th scope="col">Imagen</th>
                        <th scope="col">Descripción</th>
                        <th scope="col">Acciones</th>
                    </tr>
                </thead>
                <tbody>

                    {% for libro in libros %}

                    <tr class="">
                        <td>{{ libro.id }}</td>
                        <td>{{ libro.titulo }}</td>
                        <td>
                            {% if libro.imagen %}
                            <img src="{{ libro.imagen.url }}" height="100" alt="{{libro.titulo}}" />
                            {% else %}
                            No hay imagen disponible
                            {% endif %}
                        </td>
                        <td>{{ libro.descripcion }}</td>
                        <td> <a name="" id="" class="btn btn-info" href="{% url 'libreria:editar' %}"
                                role="button">Editar</a>
                            | <a name="" id="" class="btn btn-danger" href="#" role="button">Borrar</a>
                        </td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>

    </div>
    <div class="card-footer text-muted">Footer</div>
</div>





{% endblock %}

project/libreria/templates/libros/login.html
{% load static %}

{% block content %}
    
<form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{% url 'libreria:inicio' %}">
    <table class="table table-borderless">
        {{ form.as_table }}
        <a href="{% url 'libreria:register' %}" class="btn-danger" >Registrar Usuario</a>
    </table>
    <div class="text-center">
        <button type="submit" class="btn btn-primary">Iniciar Sesión</button>
        <a href="{% url 'libreria:inicio' %}" class="btn btn-secondary">Cancelar</a>
    </div>
</form>

{% endblock content %}

project/libreria/templates/libros/logout.html
{% load static %}


{% block content %}
    <h1 class="text-xxl-center">Gracias por visitar mi sitio</h1>
    <h3><button><a href="{% url 'libreria:inicio' %}">Retornar al sitio principal</a></button></h3>
{% endblock content %}

project/libreria/templates/libros/register.html
{% load static %}

{% block content %}
    

{% if user.is_authenticated %}
<p class="text-info ">{{mensaje}} - Bienvenido!</p>
{% endif %}

<form method="post">
    {% csrf_token %}
    <table class="table table-borderless">
        {{ form.as_table }}
    </table>
    <div class="text-center">
        <button type="submit" class="btn btn-primary">Registrarse</button>
        <a href="{% url 'libreria:inicio' %}" class="btn btn-secondary">Cancelar</a>
    </div>
</form>

{% endblock content %}

project/libreria/templates/paginas/inicio.html
{% extends "base.html" %}

{% block titulo %}  Inicio  {% endblock %}

{% block contenido %}

<div class="row align-items-md-stretch">
    <div class="col-md-6">
        <div
            class="h-100 p-5 text-white bg-primary border rounded-3"
        >
            <h2>Bienvenidos a la librería</h2>
            <button class="btn btn-outline-primary" type="button">
                <p>
                    <a class="text-black" href="{% url 'libreria:libros' %}">Empezar a ingresar libros</a>
                </p>
                <p class="lead">
                
            </button>
        </div>
    </div>
</div>


{% endblock %}

project/libreria/templates/paginas/nosotros.html
{% extends "base.html" %}

{% block titulo %}  Nosotros  {% endblock %}

{% block contenido %}

Sección de Nosotros

{% endblock %}